anchore/yardstick

- src/yardstick/tool/syft.py
The syft code structure was reorganized awhile back so yardstick needed an update to correctly build syft from source
> fix: update building syft from source to reflect reorganization of code

- src/yardstick/tool/__init__.py
- src/yardstick/tool/plugin.py
Supports loading yardstick tool plugins registered to the `yardstick.plugins.tools` entrypoint group.
Signed-off-by: Weston Steimel <weston.steimel@anchore.com>
> feat: support loading yardstick tools as plugins

- src/yardstick/artifact.py
- tests/unit/artifact_test.py
Pass the full image identifier to the `capture` function for a tool.  The current implementation does not pass in the tag portion of the identifier; however, there will be some tool implementations that require tag to be present.  Both `syft` and `grype` support passing the full image identifier, so this shouldn't break any existing tools and will enable support for future tools like `anchorectl`
Signed-off-by: Weston Steimel <weston.steimel@anchore.com>
> fix: pass full image identifier to tool.capture

- src/yardstick/tool/plugin.py
Signed-off-by: Weston Steimel <weston.steimel@anchore.com>
> fix: warning->debug for logging of discovered tool plugin entrypoints

- src/yardstick/capture.py
- src/yardstick/cli/explore/image_labels/label_manager.py
- src/yardstick/cli/explore/result.py
- src/yardstick/comparison.py
- src/yardstick/tool/__init__.py
- src/yardstick/tool/grype.py
- src/yardstick/tool/vulnerability_scanner.py
Currently there is some tool-specific package type parsing logic scattered around several places in the code.  This change moves the parsing into the tool implementation.
> refactor: move fullentry parsing logic to specific tool implementation

- src/yardstick/artifact.py
- src/yardstick/capture.py
- src/yardstick/tool/grype.py
- src/yardstick/tool/sbom_generator.py
- src/yardstick/tool/syft.py
- src/yardstick/tool/vulnerability_scanner.py
- tests/unit/artifact_test.py
Allow tools to decide how to handle capturing results based on just an image vs some other input such as an SBOM file.
For grype and syft it didn't matter because both types of input were handled the same way; however, for other tools (like anchorectl), the commands will be different and both the image name and path to the sbom will be needed.
Signed-off-by: Weston Steimel <weston.steimel@anchore.com>
> refactor: pass both image and tool_input as parameters to capture

- poetry.lock
- pyproject.toml
- src/yardstick/artifact.py
- src/yardstick/cli/cli.py
- src/yardstick/cli/config.py
- src/yardstick/store/scan_result.py
- src/yardstick/tool/grype.py
Allows for yardstick input such as:
```yaml
...
result-sets:
pr-vs-latest:
description: "latest released grype vs grype from the current build"
matrix:
images: ...
tools:
- name: grype
version: github.com/wagoodman/grype@main
...
```
enabling referencing forks of grype on different branches.
> Allow grype installations to accept alternate repo

- src/yardstick/artifact.py
Tool version may have a `@` character, thus a length limit is required.
> fix: split tool name should have a length limit

- src/yardstick/cli/explore/image_labels/cve_provider.py
- src/yardstick/tool/grype.py
- src/yardstick/utils/grype_db.py
When parsing grype results and using the grype database to find upstream CVEs for vulnerability IDs (say for GHSAs) it's important to try and use the same DB as was used in the analysis. This is not imperative, however, the current behavior is to use the system's grype database, which is overly presumptuous. It could be that the DB is out of date relative to the results, so max-year filtering will not work correctly, or that grype isn't installed at all. This PR changes the behavior to attempt to use a DB in the local yardstick tools directory first before falling back to using the system grype database.
A slightly better enhancement would be to download the specific DB used for analysis, or the latest version directly, and store in a cache directory in `.yardstick`. That can be done in a …
> Use grype DB from analysis when parsing results (if possible)

- src/yardstick/cli/config.py
- tests/unit/cli/test_config.py
Fixes loading of profiles due to downgrade of pyyaml in https://github.com/anchore/yardstick/pull/49.  Also adds a profile and ensure it loads as expected to the config test
> fix: fix profile load and add test

- src/yardstick/cli/config.py
- src/yardstick/tool/grype.py
- tests/unit/cli/test_config.py
- tests/unit/tool/test_grype.py
Add named profiles so that a grype config file path can be specified in yardstick config.
Run grype with a profile disables CPE matching, against an artifact known to have some CPE matches:
```
yardstick result capture -r test-no-cpes
2023-06-28 08:28:33,110 [INFO] capturing data result_set=test-no-cpes
2023-06-28 08:28:33,111 [INFO] using existing scan result for tool=syft@v0.84.0 image=docker.io/petabridge/lighthouse@sha256:be3b3df2f548cac599b253d9a8f2dc2d5089e9bea35b976ce22739eb9691d7ff : 5afd81cd-b7d1-411a-b63d-bacb0b126b8e
2023-06-28 08:28:33,111 [INFO] capturing data image=docker.io/petabridge/lighthouse@sha256:be3b3df2f548cac599b253d9a8f2dc2d5089e9bea35b976ce22739eb9691d7ff tool=grype@v0.63.0 profile=no_cpes
✔ Vulnerability DB        [no update available]
✔ Scanning image... …
```
> Add grype profiles

- src/yardstick/cli/label.py
- src/yardstick/store/labels.py
- tests/cli/run.sh
Previously, `yardstick label remove` didn't remove the label. Make it remove the label, and add a CLI test for this behavior.
Fixes #105.
> fix: `yardstick label remove $LABEL_ID` removes the label

- src/yardstick/tool/grype.py
- tests/unit/tool/test_grype.py
Add the ability to install `grype` from a local path. Fixes https://github.com/anchore/yardstick/issues/108.
Before this change, yardstick could be configured to install grype from a remote repository, or from a published released. But yardstick is used as part of the quality tests in grype. Therefore, when iterating on those tests, it's valuable to have a mechanism to point yardstick at a local directory that can build grype; otherwise changes have to be committed and pushed at least to a branch before yardstick can use them.
Example of the new config:
``` yaml
- name: grype
version: path:/Users/willmurphy/work/grype
takes: SBOM
```
The above config will cause yardstick to compile grype from the source found at `/Users/willmurphy/work/grype`.
Here's an example of how the version is …
> feat: install grype from path

- src/yardstick/__init__.py
- src/yardstick/capture.py
- src/yardstick/cli/cli.py
- src/yardstick/cli/config.py
- src/yardstick/cli/label.py
- src/yardstick/cli/result.py
- src/yardstick/comparison.py
- src/yardstick/store/__init__.py
- src/yardstick/store/image_lineage.py
- src/yardstick/store/label_stats.py
- src/yardstick/store/labels.py
- src/yardstick/store/result_set.py
- src/yardstick/store/scan_result.py
- src/yardstick/store/tool.py
This enables API users to optionally store the `comparison.ImageToolLabelStats` dataclass to disk, enabling reuse of the raw stats for analysis without needing to recompute from the raw data.
This additionally: 
- adds the configuration loading behavior to allow for `yardstick.yaml` files (we will still look for `.yardstick.yaml` files first).
- addresses some type hint inconsistencies.
> Add label stats store

- src/yardstick/tool/grype.py
- src/yardstick/tool/syft.py
- src/yardstick/utils/__init__.py
Similar to https://github.com/anchore/yardstick/pull/111 - Adds the ability to install syft from local path.
When making updates to the SBOM that grype consumes it's important to allow local development on syft so that developers can test their changes E2E before submitting major changes to things that might affect matching logic such as PURL/CPE.
This change allows developers to use a build based on their local `syft` to experiment with different SBOM changes.
New Config Example that uses local syft changes against changes in grype and the stable latest
```
result-sets:
example:
description: "latest released grype vs grype from the current build"
matrix:
images: *images
tools:
- name: syft
version: path:/Users/me/development/syft
produces: SBOM
refresh: false
- name: grype
version: …
```
> feat: add "path:" syntax for syft tool

- .gitignore
- pyproject.toml
- src/yardstick/__init__.py
- src/yardstick/artifact.py
- src/yardstick/capture.py
- src/yardstick/cli/config.py
- src/yardstick/comparison.py
- src/yardstick/store/labels.py
- src/yardstick/store/scan_result.py
- src/yardstick/store/tool.py
- src/yardstick/tool/grype.py
- src/yardstick/tool/syft.py
- src/yardstick/utils/__init__.py
- src/yardstick/utils/github.py
- tests/unit/tool/test_grype.py
This PR allows for a single installation of grype share multiple DB and track by the checksum of the DB (or is as `oss`).
It was noticed while working on this that:
- the root yardstick functions (such as `compare_results`) do not allow for passing an optional `store_root` as done elsewhere. This option has been added.
- some adjustments to logging where done to shorten the output, such as bump some log lines from info to debug ~and to summarize long tool and image strings intelligently~ (edit: descoped)
- add debug logging when hitting negative cases for capturing a result
- note explicitly in logging when a scan configuration is being replaced in a result set
- in the files I modified I tried to make the type hint annotations more accurate
> Allow for single grype installation with multiple shared DBs

- poetry.lock
- pyproject.toml
- src/yardstick/__init__.py
- src/yardstick/artifact.py
- src/yardstick/store/labels.py
Today it's easy to load all of the labels needed for an image and pass them into the comparison helpers. However, doing that will result in slow comparisons without it being clear as to why. In the future more logic can be added around the core objects to make it hard to misuse, but in the meantime a convenience `LabelEntryCollection` has been added by this PR to allow an API user to filter already loaded labels before a comparison is done.
Note: this uses `functools.cache` which was introduced in python 3.9, so the requirements were changed.
Additionally:
- we shouldn't try to load all of the labels just because an empty list is passed, we should distinct between None and []. This has been addressed.
- there is a lot of noise when in debug for loading labels so I removed one log line in …
> Add label collection to help with multiple label comparisons 

- .github/workflows/validations.yaml
Currently validations work best with in-repo branches, however, will not run on PRs from forks. This PR addresses this while still allowing for validations to run on the main branch on merge.
> Run validations PRs from forks

- README.md
- src/yardstick/artifact.py
- The yardstick.yaml "tools" sections needed to be updated to specify name and version of tools separately
- The config parser can now handle environment variables like `version: env:CURRENT_GRYPE_COMMIT` even if no metadata is provided (like `version: env:CURRENT_GRYPE_COMMIT+metadata`)
> Update README to correct yardstick.yaml examples and fix env var parsing

- src/yardstick/artifact.py
- src/yardstick/tool/grype.py
- tests/cli/.gitignore
- tests/cli/.yardstick.yaml
- tests/cli/Makefile
- tests/cli/run.sh
It looks like https://github.com/anchore/yardstick/pull/143/files saw a change where `ScanConfiguration` had the `detail` type contract change. This change made it so that if `version_detail`was not set in the result data structure, the datacalsses library would throw an error:
```
File "/Users/hal/development/yardstick/src/yardstick/cli/result.py", line 280, in result_descriptions
result_set_obj = store.result_set.load(result_set)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hal/development/yardstick/src/yardstick/store/result_set.py", line 50, in load
return artifact.ResultSet.from_json(data_json)  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hal/development/yardstick/tests/cli/venv/lib/python3.11/site-packages/dataclasses_json/api.py", line 63, in …
```
> fix: upgrade cli test to account for `version: v0.72.0+import-db=db.tar.gz`

- .github/workflows/release.yaml
- .github/workflows/validations.yaml
Fixes the version hints on used GitHub Actions so that dependabot can use them when creating PRs
> chore: fix actions version hint

- src/yardstick/utils/__init__.py
- tests/unit/store/test_scan_result.py
- tests/unit/utils/test_utils.py
We lean on extracting the year from vulnerability IDs in order to apply a low-pass-like filter so that newer vulnerabilities can be excluded from consideration during analysis. This expands the rules around ALAS IDs to consider the "extras" packages, here's a snippet from vunnel logs to get the idea of what kind of IDs you can see now:
```
[DEBUG] http GET https://alas.aws.amazon.com/AL2/ALASREDIS6-2024-009.html
[DEBUG] http GET https://alas.aws.amazon.com/AL2/ALASRUBY2.6-2023-001.html
[DEBUG] http GET https://alas.aws.amazon.com/AL2/ALASRUBY2.6-2023-002.html
[DEBUG] http GET https://alas.aws.amazon.com/AL2/ALASRUBY2.6-2023-003.html
[DEBUG] http GET https://alas.aws.amazon.com/AL2/ALASRUBY2.6-2023-004.html
[DEBUG] http GET https://alas.aws.amazon.com/AL2/ALASRUBY2.6-2023-005.html
[DEBUG] …
```
> Expand rules for ALAS year extraction

- src/yardstick/cli/explore/image_labels/label_selection_pane.py
- src/yardstick/cli/label.py
- src/yardstick/comparison.py
- src/yardstick/label.py
- tests/unit/test_comparison.py
When pairing label entries with vulnerability matches we should ensure that we are considering both the primary vulnerability ID as well as any related IDs (such as effective CVE) such that we are making the broadest pairing possible. This is so that if we find an `ELSA` but not the `CVE` directly, and we have a true positive label for the `CVE`, then we wouldn't count that `CVE` as a false negative (and indeed should pair up the match and true positive label entry).
This additionally places the primary vulnerability ID in the `label explore` command's label pane.
> Consider related vulnerability IDs in label comparison

- src/yardstick/cli/cli.py
Replaces `pkg_resources.get_distribution` with the recommendation from `importlib_metadata` (per https://importlib-metadata.readthedocs.io/en/latest/migration.html#pkg-resources-get-distribution); however, the string output of the Distribution object has changed, so this makes the version output match what it was before using the new Distribution object.
This allows yardstick to work with python 3.12+ where `pkg_resources` has been removed
> fix: replace pkg_resources.get_distribution

- src/yardstick/cli/config.py
- tests/unit/cli/test_config.py
Because image references are used to compute paths to state relating to the scan of the image, it's critical that the image is always completely specified.
Note: I looked into using https://github.com/anchore/yardstick/blob/main/src/yardstick/artifact.py#L390 for this parsing, but that doesn't seem to be what the object is for.
> feat: require complete and valid image ref on config parse

- .gitignore
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- src/yardstick/tool/grype.py
- tests/unit/tool/test_grype.py
This allows for processing of v1-5 and v6 archives. V6 archives are distributed in tar.zstd archives and have no metadata.json to read from. What is needed is the ability to get a unique ID for the DB being used, so calculating the checksum of the archive was done.
Sample run:
```
❯ yardstick -vvv result capture -r default
2024-12-04 17:09:36,663 [INFO] capturing data result_set=default
2024-12-04 17:09:36,663 [DEBUG] loading result set 'default' location='.yardstick/result/sets/default.json'
2024-12-04 17:09:36,664 [INFO] capturing data for request 1 of 1
2024-12-04 17:09:36,664 [DEBUG] capturing data image=docker.io/anchore/test_images:grype-quality-python-d89207b@sha256:b2b58a55c0b03c1626d2aaae2add9832208b02124dda7b7b41811e14f0fb272c …
```
> Enable importing schema v6 grype archives

- pyproject.toml
- src/yardstick/cli/display.py
- uv.lock
This will stop functioning with python 3.13 due to an import, however, the lib appears to be unmaintained. We only use this for a small bit of functionality, so I've carved that out and removed the dependency altogether.
> Remove colr dependency

- pyproject.toml
- uv.lock
seeing some build failure as 
```
... requires a different Python: 3.13.1 not in '<=3.13,>=3.11'
```
> fix: update python constraint to support py3.13.1

- src/yardstick/cli/validate.py
- uv.lock
Otherwise, it's easy for an operator to investigate the wrong image when investigating a quality gate failure.
Example of new output:
```
Results used for image docker.io/anchore/test_images@sha256:c8d664b0e728d52f57eeb98ed1899c16d3b265f02ddfb41303d7a16c31e0b0f1:
├── 86723334-feee-4a64-8d9f-5878bfb3ee34 : grype[candidate]@path:../../+import-db=db.tar.gz (candidate)  against docker.io/anchore/test_images@sha256:c8d66
4b0e728d52f57eeb98ed1899c16d3b265f02ddfb41303d7a16c31e0b0f1
└── 4b769e08-5b30-413f-a2b0-5226e03f3dd1 : grype[reference]@v0.86.1 (reference)  against docker.io/anchore/test_images@sha256:c8d664b0e728d52f57eeb98ed1899
c16d3b265f02ddfb41303d7a16c31e0b0f1
Deltas for docker.io/anchore/test_images@sha256:c8d664b0e728d52f57eeb98ed1899c16d3b265f02ddfb41303d7a16c31e0b0f1:
Match …
```
> feat: delimit between images in validate output

- .pre-commit-config.yaml
- Makefile
- src/yardstick/arrange.py
- src/yardstick/artifact.py
- src/yardstick/capture.py
- src/yardstick/cli/config.py
- src/yardstick/cli/display.py
- src/yardstick/cli/explore/image_labels/label_manager.py
- src/yardstick/cli/explore/image_labels/label_selection_pane.py
- src/yardstick/cli/explore/image_labels/result_selection_pane.py
- src/yardstick/cli/explore/image_labels/text_area.py
- src/yardstick/cli/explore/result.py
- src/yardstick/cli/label.py
- src/yardstick/comparison.py
- src/yardstick/label.py
- src/yardstick/store/labels.py
- src/yardstick/store/result_set.py
- src/yardstick/tool/grype.py
- src/yardstick/utils/__init__.py
- src/yardstick/validate/gate.py
- src/yardstick/validate/validate.py
- tests/unit/cli/test_config.py
- tests/unit/test_artifact.py
- tests/unit/tool/test_grype.py
- tests/unit/validate/test_delta.py
- tests/unit/validate/test_gate.py
- tests/unit/validate/test_validate.py
Add a make target `make format` that runs `ruff format src tests`, and call it during pre-commit. The rest of the diff is auto-generated, with the exception that ruff format put an existing `type: ignore[attr-defined]` on the wrong line when splitting up a line that was too long.
Most of the auto generated diff is line length changes. I'm happy to move the line length configured in `tool.ruff.line-length` in the pyproject.toml to try to reduce the diff size, but for a first draft I just left it what it was.
> chore: configure and run ruff format

- .github/actions/bootstrap/action.yaml
- .github/dependabot.yml
This PR remediates the following issue seen on release:
```
release-pypi    Bootstrap environment   2025-03-03T21:10:52.1653866Z ##[error]This request has been automatically failed because it uses a deprecated version of `actions/cache: 704facf57e6136b1bc63b828d79edcd491f0ee84`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
As well as updates the dependabot config to (hopefully) cover these cases.
> Update dependabot config + deprecated actions/cache dependency

- src/yardstick/tool/grype.py
- tests/unit/tool/test_grype.py
Previously, grype depended on the 'grype-db package' step, which includes the database, having been run. However, recent versions of grype can import the vulnerability.db file that results from 'grype-db build' directly. Therefore, yardstick should support configuring the grype database to be a .db file.
The main benefit is saving time in CI, where we sometimes build a grype database, and then compress it, and then import it (which includes decompressing it) on the same host. This change will allow quality gates to use less CPU time by preventing them from needing to zstd compress and then decompress the vulnerability database.
> enable configuring uncompressed database in grype db
